### PR TITLE
corrects url

### PR DESCRIPTION
**Pull request by Trybnetic**
added the wrong travis url (.com is for private and .org for public repos)

### CODE REVIEW

**Comment by Trybnetic** [comment]
Seems like we have some html code which is not clean. 

I would suggest merging this PR as travis now works and to fix the html in another PR!

@elogy what do you think?

**Comment by elogy** [comment]
Just so I get this right, Travis is failing because of the output that htmlproofer produces and this PR basically just sets the environment for travis up the right way?

**Comment by Trybnetic** [comment]
Yes.

You can also run [html-proofer](https://github.com/gjtorikian/html-proofer) locally:

```
gem install html-proofer
cd /path/to/repository/
bundle exec jekyll serve
htmlproofer _site/
```

It seems like we have 51 failures in the html code, mostly by paths.

**Comment by Trybnetic** [comment]
However, this should imho not be a problem of this PR as it only tries to fix #12

**Pull request merged**
